apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline6-pvc
  namespace: abc-bank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pipeline6-pv
  storageClassName: manual  # Must match the PV